### Post product1
POST http://localhost:5082/api/v1/products
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJlMTA0MDE0Zi1hOTE1LTQzNDktYTQ1MS03MTk5NGZhZWZmZjQiLCJyb2xlIjoiQWRtaW4iLCJlbWFpbCI6IkZhZHVsQGdtYWlsLmNvbSIsImJpcnRoZGF0ZSI6IjIwMjMtMDgtMjIiLCJuYmYiOjE2OTI3MDIyOTksImV4cCI6MTY5MjcwNDY5OSwiaWF0IjoxNjkyNzAyMjk5LCJpc3MiOiJFY29tbWVyY2UtYmFja2VuZCJ9.CFFkZB36_ZU-4r7RSa81SPcevLpXuVVjlkOu61UgQ3A

{
  "name": "BMW M3",
  "price": 56000,
  "description": "An amazing car very nice. Can go anywhere and immerse you in it, perfect for road trips and daily commutes.",
  "images": [
    {
      "createdAt": "2023-08-22T10:38:06.653Z",
      "updatedAt": "2023-08-22T10:38:06.653Z",
       "id": "3fa82f65-5727-7292-b3fc-6c963f33afa6",
      "link": "https://example.com/Electronics/smart_led_tv.jpg"
    }
  ],
  "stockQuantity": 3,
  "categoryId": "f67d485d-d0f9-4905-8e88-1ac9569ce160"
}


### Post product2
POST http://localhost:5082/api/v1/products
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJhNGE2ZDA1Yy01YmVmLTQ1YzQtYTE0MC1lZTQ5OGIwYmMzNDkiLCJyb2xlIjoiQWRtaW4iLCJlbWFpbCI6IkZhZHVsQGdtYWlsLmNvbSIsImJpcnRoZGF0ZSI6IjIwMjMtMDgtMTYiLCJuYmYiOjE2OTIyMDUzMjgsImV4cCI6MTY5MjIwNzcyOCwiaWF0IjoxNjkyMjA1MzI4LCJpc3MiOiJFY29tbWVyY2UtYmFja2VuZCJ9.rsMLKrLtk0Rm8MYZzauuCNEpf2u0mrXywpq25hSOFxc

 {
    "name": "Glowing Skin Cream",
    "price": 25.50,
    "description": "A rejuvenating cream that revitalizes skin and offers a radiant glow.",
    "images": [
      {
        "createdAt": "2023-08-15T12:11:45.900Z",
        "updatedAt": "2023-08-15T12:11:45.900Z",
        "id": "91a2b3c4-5678-9101-1121-314151617191",
        "link": "https://example.com/products/images/skin_cream.jpg"
      }
    ],
    "stockQuantity": 250,
    "categoryId": ""
  }


### Post product2
GET  http://localhost:5082/api/v1/products
content-type: application/json
//Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJhNGE2ZDA1Yy01YmVmLTQ1YzQtYTE0MC1lZTQ5OGIwYmMzNDkiLCJyb2xlIjoiQWRtaW4iLCJlbWFpbCI6IkZhZHVsQGdtYWlsLmNvbSIsImJpcnRoZGF0ZSI6IjIwMjMtMDgtMTYiLCJuYmYiOjE2OTIyMDUzMjgsImV4cCI6MTY5MjIwNzcyOCwiaWF0IjoxNjkyMjA1MzI4LCJpc3MiOiJFY29tbWVyY2UtYmFja2VuZCJ9.rsMLKrLtk0Rm8MYZzauuCNEpf2u0mrXywpq25hSOFxc
